"""Lesson 30 - Bias Blind Spot (algorithmic bias and fairness impossibility)."""

from __future__ import annotations

CONTENT: dict[str, dict[str, list[str]]] = {
    "pl": {
        "theory": [
            "Bias algorytmiczny to nie blad programisty - to historia zakodowana w danych. Algorytm kredytowy uczy sie na historycznych decyzjach bankow, ktore przez dziesieciolecia odmawialy kredytow mieszkancom konkretnych dzielnic (redlining). Termin pochodzi od HOLC (Home Owners' Loan Corporation, 1933-1954), ktora kolorowala mapy dzielnic na czerwono - odmowy kredytow w tych strefach trwaly przez pokolenia. Nawet bez atrybutu 'rasa' model odtwarza te wzorce, bo uczy sie z danych ktore same sa skutkiem dyskryminacji.",
            "Proxy features to cechy, ktore nie sa chronionym atrybutem, ale silnie koreluja z przynaleznoscia do grupy chronionej. Przyklad: kod pocztowy koreluje z rasa ze wzgledu na historyczne praktyki segregacji mieszkaniowej. Usuniecie atrybutu 'rasa' z modelu nie usuwa dyskryminacji, bo 'kod pocztowy' niesie ta sama informacje (r=0.71). Joy Buolamwini (MIT, Gender Shades 2018) pokazala, ze komercyjne systemy rozpoznawania twarzy popelnialy bledy o 34.7 pp czesciej dla ciemnoskore kobiety niz dla jasnoskore mezczyzny - zadna z firm nie uzywala plci ani rasy jako cech modelu, a mimo to bias byl systemowy.",
            "Trade-off bias vs dokladnosc: usuniecie proxy features zmniejsza bias, ale rowniez zmniejsza zdolnosc modelu do rozrozniana ryzyka. Usuniecie kodu pocztowego obniza bias z 33pp do 21pp, ale dokladnosc spada z 79% do 76%. Usuniecie kolejnych proxy moze obnizyc bias do 9pp, ale dokladnosc moze spasc do 58%. To nie jest blad implementacji - to matematyczny kompromis wynikajacy z korelacji cech z wynikiem.",
            "Twierdzenie niemozliwosci sprawiedliwosci (Chouldechova 2017, Kleinberg i in. 2016): gdy bazowe wskazniki sa rozne w dwoch grupach (tj. jedna grupa ma historycznie gorsze wyniki), nie istnieje algorytm, ktory jednoczesnie spelnia: (1) parytet demograficzny - rowne wskazniki zatwierdzenia, (2) rowne szanse - rowny wskaznik falszywi negatywni (FNR), (3) kalibracje - jesli model mowi 70%, faktycznie 70% splaci kredyt. Spelnienie jednego kryterium matematycznie wyklucza pozostale dwa. Obydwa artykuly ukazaly sie niezaleznie w tym samym roku - to klasyczny przyklad rownoczesnego odkrycia.",
            "COMPAS (Correctional Offender Management Profiling for Alternative Sanctions) - algorytm oceny ryzyka recydywizmu uzywany w ponad 400 sadach w USA. Badanie ProPublica (Angwin i in., 2016) wykazalo, ze falszywie klasyfikuje czarnych oskarzonej jako wysokie ryzyko 2x czesciej niz bialych. Northpointe (tworca COMPAS) odpowiedzial, ze model jest skalibrowany. Obaj mieli racje: to jest przyklad twierdzenia niemozliwosci w praktyce - przy roznych bazowych wskaznikach recydywizmu, kalibracja i rowny FPR sa niemozliwe do jednoczesnego spelnienia.",
            "EU AI Act (2024): algorytmy do oceny kredytowej naleza do kategorii wysokiego ryzyka (Annex III, pkt 5b). Wymagania: dokumentacja techniczna, ocena ryzyka, logging, nadzor ludzki i prawo do wyjasnienia dla osoby, ktora dostala odmowe. Ustawa nie narzuca konkretnego kryterium sprawiedliwosci - pozostawia to dostawcy. To sprawia, ze 'compliance' nie rozwiazuje problemu politycznego wyboru miedzy metrykami sprawiedliwosci.",
        ],
        "notes": [
            "Amazon (2015-2018) uzywala wewnetrznego algorytmu rekrutacyjnego opartego na 10-letniej historii zatrudnien. Model nauczyl sie penalizowac CV zawierajace slowo 'kobiece' i nazwy uczelni zenskich - bo historycznie rekrutowano glownie mezczyzn. Amazon wycofal algorytm w 2018 roku po tym jak problema ujawnila Reuters. To przyklad jak historyczne dane moga zakodowac przeszla dyskryminacje w przyszlych decyzjach.",
            "Fairness przez grupy: bias mierzony na poziomie grup moze ukrywac bias na poziomie podgrup (subgroup fairness). Model moze byc 'sprawiedliwy' dla kobiet i dla osob ciemnoskore oddzielnie, ale znacznie gorzej dzialac dla ciemnoskore kobiet - to tzw. intersectionality w kontekscie ML. Kearns i in. (2018) wprowadzili pojecie 'audited fairness' dla audytu na wszystkich mozliwych podgrupach.",
        ],
        "tasks": [
            "Po usunieciu kodu pocztowego i wskaznika dlugu bias nie zniknal calkowicie. Jakie inne cechy moglby byc proxy features w danych o kredytach? Wymien dwie i uzasadnij, dlaczego moglby korelowac z przynaleznoscia do grupy chronionej.",
            "W Akcie 3 dostepne sa trzy kryteria sprawiedliwosci. Ktore z trzech (parytet demograficzny, rowne szanse, kalibracja) wybraby bank? Rzecznik rownosci? Osoba skladajaca wniosek kredytowy z grupy mniejszosciowej? Uzasadnij kazdy wybor z perspektywy interesu danego aktora.",
            "Znajdz jeden realny przyklad algorytmu uzytego w decyzjach o wplywie na zycie ludzi (kredyty, rekrutacja, sady, sluzba zdrowia), w ktorym pojawily sie oskarzenia o bias. Ktore kryterium sprawiedliwosci bylo naruszone? Czy problem wynikal z proxy features czy z historycznych danych?",
        ],
    },
    "en": {
        "theory": [
            "Algorithmic bias is not a programmer error - it is history encoded in data. A credit algorithm learns from historical bank decisions that for decades denied loans to residents of specific neighborhoods (redlining). The term comes from the HOLC (Home Owners' Loan Corporation, 1933-1954), which color-coded neighborhood maps in red - loan denials in those zones persisted for generations. Even without a 'race' attribute, the model reproduces these patterns because it learns from data that is itself the product of discrimination.",
            "Proxy features are attributes that are not themselves protected but strongly correlate with protected group membership. Example: zip code correlates with race due to historical residential segregation. Removing 'race' from the model does not remove discrimination, because 'zip code' carries the same information (r=0.71). Joy Buolamwini (MIT, Gender Shades 2018) showed that commercial face recognition systems made errors 34.7 pp more often for dark-skinned women than for light-skinned men - none of the companies used gender or race as model features, yet the bias was systemic.",
            "Bias vs accuracy trade-off: removing proxy features reduces bias but also reduces the model's ability to distinguish risk. Removing zip code lowers bias from 33pp to 21pp, but accuracy falls from 79% to 76%. Removing further proxies may lower bias to 9pp, but accuracy may fall to 58%. This is not an implementation error - it is a mathematical trade-off arising from features correlating with outcome.",
            "Fairness impossibility theorem (Chouldechova 2017, Kleinberg et al. 2016): when base rates differ between two groups (i.e., one group has historically worse outcomes), no algorithm can simultaneously satisfy: (1) demographic parity - equal approval rates, (2) equal opportunity - equal false negative rate (FNR), (3) calibration - if the model says 70%, actually 70% will repay. Satisfying one criterion mathematically excludes the other two. Both papers appeared independently in the same year - a classic simultaneous discovery.",
            "COMPAS (Correctional Offender Management Profiling for Alternative Sanctions) - a recidivism risk scoring algorithm used in over 400 US courts. A ProPublica study (Angwin et al., 2016) found it falsely classifies Black defendants as high risk 2x more often than white defendants. Northpointe (COMPAS creator) responded that the model is calibrated. Both were correct: this is the impossibility theorem in practice - with different base recidivism rates, calibration and equal FPR cannot both be satisfied.",
            "EU AI Act (2024): credit scoring algorithms belong to the high-risk category (Annex III, point 5b). Requirements: technical documentation, risk assessment, logging, human oversight, and right to explanation for anyone who receives a denial. The law does not impose a specific fairness criterion - it leaves that to the provider. This means 'compliance' does not resolve the political choice between fairness metrics.",
        ],
        "notes": [
            "Amazon (2015-2018) used an internal recruitment algorithm trained on 10 years of hiring history. The model learned to penalize CVs containing the word 'women's' and names of women's colleges - because historically mostly men had been hired. Amazon withdrew the algorithm in 2018 after Reuters broke the story. This illustrates how historical data can encode past discrimination into future decisions.",
            "Group fairness can hide subgroup bias. A model may be 'fair' for women and for dark-skinned people separately, but perform much worse for dark-skinned women - this is intersectionality in ML. Kearns et al. (2018) introduced 'rich subgroup fairness' for auditing across all possible subgroups defined by combinations of attributes.",
        ],
        "tasks": [
            "After removing zip code and debt ratio, bias did not disappear completely. What other features could be proxy features in credit data? Name two and explain why they might correlate with protected group membership.",
            "In Act 3 three fairness criteria are available. Which of the three (demographic parity, equal opportunity, calibration) would a bank choose? An equality advocate? A minority group loan applicant? Justify each choice from the perspective of each actor's interests.",
            "Find one real-world example of an algorithm used in life-affecting decisions (credit, hiring, courts, healthcare) where bias allegations arose. Which fairness criterion was violated? Did the problem stem from proxy features or historical data?",
        ],
    },
}
