# src/cognitive_data_arcade/games/architects_trial/domain_data.py
"""Domain data for The Architect's Trial. No pygame imports."""
from __future__ import annotations
from cognitive_data_arcade.games.architects_trial.game_state import DecisionCard

def _card(key, label, description, note, note_color, f, c, e) -> DecisionCard:
    return DecisionCard(
        key=key, label=label, description=description,
        note=note, note_color=note_color,
        fairness_delta=f, compliance_delta=c, effectiveness_delta=e,
    )

DOMAIN_DATA: dict[str, dict] = {
    "social": {
        "title": "System Ryzyka dla Dzieci",
        "institution": "Urzad ds. Opieki Spolecznej",
        "act1_question": "Jakie zrodla danych wybierasz?",
        "act2_question": "Pod jaka metryke optymalizujesz model?",
        "act3_question": "Jak definiujesz sukces systemu?",
        "act1_cards": [
            _card("registries", "Rejestry miejskie",
                  "Historia zasilkow, mandatow, interwencji socjalnych.",
                  "Dostepne od zaraz", "green", 10, 20, 10),
            _card("registries_social", "Rejestry + social media",
                  "Posty, aktywnosc, siec znajomych rodzin.",
                  "Etycznie ryzykowne", "red", -15, -5, 25),
            _card("registries_health", "Rejestry + dane zdrowotne",
                  "Wizyty lekarskie, diagnozy, recepty.",
                  "RODO: wymagana zgoda", "orange", 0, -10, 20),
        ],
        "act2_cards": [
            _card("minimize_fn", "Minimalizuj FN",
                  "Nie przegap zadnego zagrozenia. Wysoka czulosc.",
                  "Wiecej falsz. alarmow", "orange", -20, 0, 30),
            _card("minimize_fp", "Minimalizuj FP",
                  "Nie nekaj niewinnych rodzin. Wysoka specyficznosc.",
                  "Mozesz przeoczyc zagrozenie", "orange", 25, 0, -15),
            _card("balance_f1", "Balans F1",
                  "Kompromis miedzy czuloscia a specyficznoscia.",
                  "Umiarkowane w obu kierunkach", "green", 10, 20, 10),
        ],
        "act3_cards": [
            _card("kpi_interventions", "KPI: liczba interwencji",
                  "System oceniany po tym ile razy wyslal pracownika.",
                  "Gameable metric", "red", -10, -5, 20),
            _card("kpi_outcomes", "KPI: wyniki po roku",
                  "Czy dzieci z interwencja maja sie lepiej po 12 miesiacach?",
                  "Trudne do zmierzenia", "orange", 20, 15, -5),
            _card("kpi_cost", "KPI: koszt/przypadek",
                  "Efektywnosc kosztowa jako glowny wskaznik.",
                  "Moze faworyzowac latwe przypadki", "red", -15, -5, 15),
        ],
        "act4_consequences": {
            "registries": "Dane z rejestrow daly solidna baze. Pokrycie niekompletne dla nowych rodzin w miescie.",
            "registries_social": "Dane social media ujawnily przynaleznosc polityczna 3 rodzin. To nie byl cel systemu.",
            "registries_health": "Urzad nie mial zgody RODO na dane zdrowotne. Audyt Inspektora Ochrony Danych trwa.",
            "minimize_fn": "System zglosil 340 ryzykownych rodzin. 280 to falszywe alarmy -- glownie z Pragi Pd.",
            "minimize_fp": "System przegapil 12 realnych przypadkow zagrozen w ciagu 6 miesiecy.",
            "balance_f1": "Wyniki umiarkowane w obu kierunkach. Zespol chce wiekszej czulosci.",
            "kpi_interventions": "Urzednicy wybieraja latwe przypadki by podniesc liczbe interwencji.",
            "kpi_outcomes": "Rok to za malo. Dane o wynikach sa niekompletne, projekt kwestionowany.",
            "kpi_cost": "Najtansze interwencje trafiaja do zamozniejszych dzielnic. Biedniejsze czekaja.",
        },
    },
    "hiring": {
        "title": "System Rekrutacji AI",
        "institution": "Magistrat / Sluzba Cywilna",
        "act1_question": "Jakie dane o kandydatach zbierasz?",
        "act2_question": "Na czym uczy sie Twoj model?",
        "act3_question": "Jak mierzysz sukces rekrutacji?",
        "act1_cards": [
            _card("h_historical_cv", "CV z 10 lat",
                  "Historia zatrudnienia, wyksztalcenie, przerwy w pracy.",
                  "Bias historyczny", "orange", -15, 10, 20),
            _card("h_blind_cv", "Anonimizowane CV",
                  "Bez imienia, plci, adresu i zdjecia.",
                  "Rekomendowane przez RODO", "green", 30, 15, -10),
            _card("h_assessments", "Testy kompetencji",
                  "Standaryzowane testy online bez danych osobowych.",
                  "Wymaga dostepu do internetu", "orange", -5, 15, 25),
        ],
        "act2_cards": [
            _card("h_past_performance", "Ucz sie na dotychczasowych pracownikach",
                  "Model wykrywa pattern dobrego pracownika z historii.",
                  "Amazon 2018 -- bias plciowy", "red", -25, 0, 30),
            _card("h_diverse_criteria", "Wagi wielokryterialne",
                  "Kompetencje + roznorodnosc + doswiadczenie bez proxy.",
                  "Wolniejsza rekrutacja", "green", 20, 20, -10),
            _card("h_structured_interview", "Model preselekcji + rozmowa",
                  "AI tylko shortlistuje, czlowiek podejmuje finalna decyzje.",
                  "Human in the loop", "green", 15, 25, -5),
        ],
        "act3_cards": [
            _card("h_kpi_speed", "KPI: czas rekrutacji",
                  "Jak szybko obsadzamy stanowisko od ogloszenia.",
                  "Moze preferowac oczywistych kandydatow", "orange", -15, -5, 25),
            _card("h_kpi_retention", "KPI: retencja po 2 latach",
                  "Czy pracownicy zostaja i awansuja?",
                  "Trudne do wczesnego pomiaru", "orange", -5, 10, 20),
            _card("h_kpi_diversity", "KPI: roznorodnosc zatrudnionych",
                  "Wskaznik reprezentacji grup niedoreprezentowanych.",
                  "Wymaga monitorowania", "green", 30, 10, -10),
        ],
        "act4_consequences": {
            "h_historical_cv": "System odrzuca kandydatki po urlopie macierzynskim -- przerwa w CV obniza score.",
            "h_blind_cv": "Anonimizacja wydluzyla proces rekrutacji o 40%. Dzial HR jest niezadowolony.",
            "h_assessments": "Testy online faworyzuja kandydatow z szybkim internetem i ciszonym miejscem.",
            "h_past_performance": "Model odrzuca kobiety -- nauczyl sie wzorca z danych sprzed 2010 roku.",
            "h_diverse_criteria": "Rekrutacja wolniejsza, ale skargi na dyskryminacje spadly o 60%.",
            "h_structured_interview": "Kandydaci finalni sa lepiej dobrani. HR twierdzi ze AI jest zbedne.",
            "h_kpi_speed": "Rekrutacja szybsza, ale nowi pracownicy odchodza po 6 miesiacach.",
            "h_kpi_retention": "KPI trudny do wczesnego zmierzenia. Projekt finansowo kwestionowany.",
            "h_kpi_diversity": "Wskaznik roznorodnosci wymaga 15% wiekszego budzetu na outreach.",
        },
    },
    "triage": {
        "title": "System Triage SOR",
        "institution": "Szpital Miejski",
        "act1_question": "Jakie dane medyczne zbierasz?",
        "act2_question": "Pod co optymalizujesz kolejke?",
        "act3_question": "Jak definiujesz sukces systemu?",
        "act1_cards": [
            _card("t_vitals", "Tylko pomiary zyciowe",
                  "Tetno, cisnienie, saturacja, temperatura.",
                  "Obiektywne i szybkie", "green", -5, 20, 20),
            _card("t_vitals_history", "Pomiary + historia chorob",
                  "Choroby przewlekle, poprzednie pobyty, leki.",
                  "Ryzyko proxy bias (wiek)", "orange", -10, 15, 30),
            _card("t_vitals_social", "Pomiary + dane socjoekonomiczne",
                  "Ubezpieczenie, kod pocztowy, status zatrudnienia.",
                  "Proxy rasy i statusu", "red", -25, -15, 35),
        ],
        "act2_cards": [
            _card("t_minimize_mortality", "Optymalizuj pod przezywalosc",
                  "Minimalizuj ryzyko zgonu w ciagu 24h.",
                  "Faworyzuje mlodszych pacjentow", "orange", -20, 0, 35),
            _card("t_qaly", "Optymalizuj pod QALY",
                  "Lata zycia skorygowane jakoscia jako miara sukcesu.",
                  "Dyskryminuje niepelnosprawnych", "red", -15, -10, 25),
            _card("t_equal_waiting", "Rowny czas oczekiwania",
                  "Minimalizuj roznice czasu oczekiwania miedzy grupami.",
                  "Mozliwy wzrost smiertelnosci", "orange", 30, 15, -15),
        ],
        "act3_cards": [
            _card("t_kpi_mortality", "KPI: smiertelnosc w SOR",
                  "Odsetek zgonow podczas pobytu na oddziale.",
                  "Nie obejmuje zgonow po wypisie", "orange", -10, -5, 30),
            _card("t_kpi_waiting", "KPI: sredni czas oczekiwania",
                  "Sredni czas od przyjecia do pierwszego badania.",
                  "Maskuje wartosci odstajace", "orange", -15, 10, 20),
            _card("t_kpi_equity", "KPI: rownosc wynikow",
                  "Porownanie smiertelnosci i czasu oczekiwania miedzy grupami.",
                  "Wymaga wiecej personelu", "green", 25, 15, -10),
        ],
        "act4_consequences": {
            "t_vitals": "Baza tylko na pomiarach dziala dobrze dla ostrych przypadkow. Choroby chroniczne niedoreprezentowane.",
            "t_vitals_history": "Historia chorob ujawnia wiek i choroby. Mlodsi automatycznie w kolejce pierwsi.",
            "t_vitals_social": "Ubezpieczenie prywatne stalo sie proxy statusu. Bogatsi czekaja krocej o 34%.",
            "t_minimize_mortality": "Seniorzy z wieloma schorzeniami trafiaja na koniec kolejki mimo ostrego bolu.",
            "t_qaly": "Pacjenci z niepelnosprawnoscia oceniani jako nizsza jakosc zycia -- skargi do rzecznika.",
            "t_equal_waiting": "Czas oczekiwania wyrownany, ale smiertelnosc w SOR wzrosla o 4% w pierwszym kwartale.",
            "t_kpi_mortality": "Wskaznik smiertelnosci dobry, ale nie uwzglednia zgonow 48h po wypisie.",
            "t_kpi_waiting": "Krotki sredni czas maskuje 6-godzinne czekanie dla 10% pacjentow.",
            "t_kpi_equity": "Rownosc wynikow wymaga 30% wiecej personelu. Szpital nie ma budzetu.",
        },
    },
}
